"""
gsc_aspose.com.py
=======================
Fetches Google Search Console data across 3 time windows (Last 3 months,
Last 6 months, Last 12 months) and produces two CSV files:

  csv/comparison_all_periods.csv   — merged wide table, one row per URL,
                                     columns for each period's metrics plus
                                     trend pattern label.

  csv/<brand>_candidates.csv       — filtered to URLs that are genuine
                                     optimization candidates based on
                                     multi-period pattern analysis.

Exclusion rules applied to both outputs:
  • Non-English language-prefix URLs  (reuses has_language_prefix)
  • High-click URLs: any URL with >= HIGH_CLICK_THRESHOLD clicks in ANY
    period is excluded from the candidates file (still kept in all_periods).
  • CTR band: 1% – 4% in the ANCHOR period (12 months) for candidates.
  • Position gate: any URL with position < POSITION_THRESHOLD in any
    available period is excluded from the candidates file.

The candidates CSV adds two final columns:
  • "Recommended Action Reason" — short human-readable rationale
  • "Recommended Action" — structured code used by the optimizer

When LLM credentials are available, the recommendation is generated by the
LLM from clicks, impressions, position, trend pattern, and age context. If
the LLM is unavailable, a deterministic fallback keeps the pipeline working.

Pattern labels (column "trend_pattern"):
  improving          CTR rises across all three windows  (3m > 6m > 12m)
  declining          CTR falls across all three windows  (3m < 6m < 12m)
  continuously_good  CTR >= CTR_GOOD_THRESHOLD in all three windows
  continuously_bad   CTR <  CTR_BAD_THRESHOLD  in all three windows
  volatile           none of the above
  insufficient_data  fewer than 2 periods have data

Usage
-----
  python gsc_aspose.com.py

Environment variables (optional overrides):
  BLOG_CONTENT_ROOT   path to local content repo for publish-date enrichment
  GSC_WEB_APP_URL / GSC_WEB_APP_SECRET  Google Apps Script endpoint and shared secret
  ASPOSE_WEB_APP_URL  legacy compatibility alias for the endpoint
  ASPOSE_SPREADSHEET_ID
  PROFESSIONALIZE_API_KEY_OPTIMIZER / PROFESSIONALIZE_API_KEY
  PROFESSIONALIZE_BASE_URL / PROFESSIONALIZE_LLM_MODEL
                      optional LLM settings for "Recommended Action"
"""

import os
import sys
import json
import re
import requests
import pandas as pd
from datetime import datetime, timedelta
from urllib.parse import urlparse

import searchconsole
from dotenv import load_dotenv
from openai import OpenAI

from gsc_processing_utils import (
    has_language_prefix,
    select_best_days_since_map,
    url_to_path,
)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

load_dotenv()

PROPERTY_URL = os.getenv("GSC_PROPERTY_URL", "https://blog.aspose.com/")
PROPERTY_HOST = urlparse(PROPERTY_URL).hostname or urlparse(PROPERTY_URL).netloc or "blog.aspose.com"
PROPERTY_HOST = PROPERTY_HOST.split(":", 1)[0].lower()
CONTENT_REPO_NAME = os.getenv(
    "GSC_CONTENT_REPO_NAME",
    f"{(os.getenv('BLOG_BRAND') or PROPERTY_HOST.replace('blog.', '').split('.', 1)[0]).strip().lower().replace('-', '_')}-blog",
)
HIGH_CLICK_THRESHOLD = 500       # URLs with >= this clicks in ANY period are
                                  # excluded from the candidates CSV
CTR_THRESHOLD      = 0.01        # 1%  — lower bound for candidate CTR filter
CTR_MAX_THRESHOLD  = 0.04        # 4%  — upper bound
CTR_GOOD_THRESHOLD = 0.03        # 3%  — used to label "continuously_good"
CTR_BAD_THRESHOLD  = 0.01        # 1%  — used to label "continuously_bad"
POSITION_THRESHOLD = 15          # URLs with position < this value are
                                 # excluded from the candidates CSV

RECOMMENDED_ACTION_TITLE_META = "TITLE_META"
RECOMMENDED_ACTION_FULL_REFRESH = "FULL_REFRESH"
RECOMMENDED_ACTION_CONTENT_PLUS_META = "CONTENT_PLUS_META"
RECOMMENDED_ACTION_COLUMN = "Recommended Action"
RECOMMENDED_ACTION_REASON_COLUMN = "Recommended Action Reason"
RECOMMENDED_ACTION_CODES = {
    RECOMMENDED_ACTION_TITLE_META,
    RECOMMENDED_ACTION_FULL_REFRESH,
    RECOMMENDED_ACTION_CONTENT_PLUS_META,
}

LLM_API_KEY = os.getenv("PROFESSIONALIZE_API_KEY_OPTIMIZER") or os.getenv("PROFESSIONALIZE_API_KEY")
LLM_BASE_URL = os.getenv("PROFESSIONALIZE_BASE_URL", "https://llm.professionalize.com/v1")
LLM_MODEL = os.getenv("PROFESSIONALIZE_LLM_MODEL", "gpt-oss")
RECOMMENDATION_CLIENT = None
MAX_REASON_WORDS = 8

if LLM_API_KEY:
    try:
        RECOMMENDATION_CLIENT = OpenAI(api_key=LLM_API_KEY, base_url=LLM_BASE_URL)
    except Exception as exc:
        print(f"Warning: recommendation LLM client unavailable: {exc}")

# Time windows: (label, days_back)
PERIODS = [
    ("3m",  90),
    ("6m",  180),
    ("12m", 365),
]

CSV_FOLDER = "csv"
WEB_APP_URL = os.getenv("GSC_WEB_APP_URL") or os.getenv("ASPOSE_WEB_APP_URL")
WEB_APP_SHARED_SECRET = os.getenv("GSC_WEB_APP_SECRET") or os.getenv("APPS_SCRIPT_SHARED_SECRET")
SPREADSHEET_ID = os.getenv("GSC_SPREADSHEET_ID") or os.getenv("ASPOSE_SPREADSHEET_ID")
SHEET_NAME = os.getenv("GSC_SHEET_NAME", "blog.aspose.com")
UPLOAD_CHUNK_SIZE = 3000


def derive_candidate_csv_stem(property_url: str) -> str:
    """Derive the candidate CSV stem from the blog property or override."""
    exact_stem = os.getenv("GSC_CANDIDATE_FILE_STEM")
    if exact_stem:
        return exact_stem.strip().lower().replace(" ", "_")

    override = os.getenv("BLOG_BRAND")
    if override:
        return override.strip().lower().replace("-", "_").replace(" ", "_")

    stem_override = os.getenv("GSC_CANDIDATE_STEM")
    if stem_override:
        return stem_override.strip().lower().replace("-", "_").replace(" ", "_")

    parsed = urlparse(property_url)
    host = (parsed.netloc or parsed.path or property_url or "").lower()
    host = host.split(":", 1)[0]
    if host.startswith("www."):
        host = host[4:]
    if host.startswith("blog."):
        host = host[5:]

    brand = host.split(".", 1)[0] if host else "aspose"
    brand = brand.strip().lower().replace("-", "_")
    return brand or "aspose"


def clean_row_record(record: dict) -> dict:
    """Convert pandas/numpy values into JSON-safe primitives."""
    cleaned = {}
    for key, value in record.items():
        if pd.isna(value):
            cleaned[key] = None
            continue
        if isinstance(value, pd.Timestamp):
            cleaned[key] = value.isoformat()
            continue
        if hasattr(value, "item"):
            try:
                value = value.item()
            except Exception:
                pass
        cleaned[key] = value
    return cleaned


def send_to_google_sheets(rows, is_first_chunk=True):
    """Send rows to the Apps Script receiver."""
    if not WEB_APP_URL:
        print("  Upload failed: GSC_WEB_APP_URL is not set")
        return False, None
    if not SPREADSHEET_ID:
        print("  Upload failed: GSC_SPREADSHEET_ID is not set")
        return False, None
    if not WEB_APP_SHARED_SECRET:
        print("  Upload failed: GSC_WEB_APP_SECRET (or APPS_SCRIPT_SHARED_SECRET) is not set")
        return False, None

    payload = {
        "action": "import_data",
        "spreadsheetId": SPREADSHEET_ID,
        "sheetName": SHEET_NAME,
        "rows": rows,
        "clearExisting": is_first_chunk,
        "shared_secret": WEB_APP_SHARED_SECRET,
        "token": WEB_APP_SHARED_SECRET,
    }

    try:
        response = requests.post(
            WEB_APP_URL,
            headers={"Content-Type": "application/json"},
            data=json.dumps(payload),
            timeout=60,
        )
    except requests.exceptions.Timeout:
        print("  Upload timed out")
        return False, None
    except Exception as exc:
        print(f"  Upload failed: {exc}")
        return False, None

    if response.status_code != 200:
        print(f"  Upload HTTP error {response.status_code}: {response.text[:200]}")
        return False, None

    result = response.json()
    if not result.get("success"):
        print(f"  Upload error: {result.get('error', 'unknown error')}")
        return False, result

    print(f"  Upload ok: {result.get('message')}")
    print(f"  Total rows now in sheet: {result.get('total_rows_in_sheet', 0)}")
    return True, result


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def authenticate():
    """Authenticate with Google Search Console."""
    if os.path.exists("credentials.json"):
        account = searchconsole.authenticate(credentials="credentials.json")
    else:
        account = searchconsole.authenticate(client_config="client_secret.json")
        account.serialize_credentials("credentials.json")
    return account


def fetch_period(webproperty, days_back: int, label: str) -> pd.DataFrame:
    """Fetch page-level GSC data for a rolling window of *days_back* days."""
    end_date   = datetime.now().date()
    start_date = end_date - timedelta(days=days_back)
    print(f"  [{label}] Fetching {start_date} → {end_date} …", end=" ", flush=True)

    report = webproperty.query.range(start_date, end_date).dimension("page").get()
    df = pd.DataFrame(report)
    print(f"{len(df):,} rows")

    if df.empty:
        return pd.DataFrame(columns=["page", "clicks", "impressions", "ctr", "position"])

    if "ctr" not in df.columns:
        df["ctr"] = df["clicks"] / df["impressions"].replace(0, 1)

    # Keep only the target property and English URLs
    df = df[df["page"].str.contains(PROPERTY_HOST, na=False)]
    df = df[~df["page"].apply(has_language_prefix)]

    return df[["page", "clicks", "impressions", "ctr", "position"]].copy()


def label_trend(row, period_labels):
    """
    Assign a trend pattern based on CTR across available periods.
    Periods are ordered shortest → longest: 3m, 6m, 12m.
    """
    ctr_cols = [f"ctr_{p}" for p in period_labels]
    ctrs = [row.get(c) for c in ctr_cols]
    available = [(p, v) for p, v in zip(period_labels, ctrs) if pd.notna(v)]

    if len(available) < 2:
        return "insufficient_data"

    values = [v for _, v in available]

    # Continuously good / bad (all available periods)
    if all(v >= CTR_GOOD_THRESHOLD for v in values):
        return "continuously_good"
    if all(v < CTR_BAD_THRESHOLD for v in values):
        return "continuously_bad"

    # Improving: shorter window CTR > longer window CTR
    # available[0] = most recent short window, available[-1] = oldest long window
    if all(values[i] > values[i + 1] for i in range(len(values) - 1)):
        return "improving"

    # Declining
    if all(values[i] < values[i + 1] for i in range(len(values) - 1)):
        return "declining"

    return "volatile"


def min_position_across_periods(row, period_labels):
    """Return the best ranking position observed across available periods."""
    position_cols = [f"position_{p}" for p in period_labels]
    positions = pd.to_numeric([row.get(c) for c in position_cols], errors="coerce")
    valid_positions = positions[~pd.isna(positions)]
    if len(valid_positions) == 0:
        return float("nan")
    return float(valid_positions.min())


def build_recommendation_signature(row, period_labels):
    """Build a stable signature for caching LLM recommendations."""
    key_fields = []
    for label in period_labels:
        key_fields.extend([
            f"{label}:{row.get(f'clicks_{label}', '')}",
            f"{label}:{row.get(f'impressions_{label}', '')}",
            f"{label}:{row.get(f'ctr_{label}', '')}",
            f"{label}:{row.get(f'position_{label}', '')}",
        ])
    key_fields.extend([
        f"trend:{row.get('trend_pattern', '')}",
        f"minpos:{row.get('min_position_any_period', '')}",
        f"days:{row.get('days_since_published', '')}",
    ])
    return "|".join(map(str, key_fields))


def normalize_recommended_action_code(action_text: str) -> str | None:
    """Normalize free-form LLM output into one of the structured action codes."""
    if not action_text:
        return None

    text = " ".join(str(action_text).strip().split())
    upper = text.upper()
    compact = re.sub(r"[^A-Z0-9]+", "_", upper).strip("_")
    if compact in RECOMMENDED_ACTION_CODES:
        return compact

    lowered = text.lower()
    if "content refresh + title/meta refresh" in lowered:
        return RECOMMENDED_ACTION_CONTENT_PLUS_META
    if "title/meta refresh" in lowered:
        return RECOMMENDED_ACTION_TITLE_META
    if "full content refresh" in lowered:
        return RECOMMENDED_ACTION_FULL_REFRESH

    return None


def fallback_recommended_action(row) -> dict:
    """Deterministic recommendation used when the LLM is unavailable."""
    position = pd.to_numeric(row.get("min_position_any_period"), errors="coerce")
    ctr = pd.to_numeric(row.get("ctr_12m"), errors="coerce")
    trend = str(row.get("trend_pattern", "volatile")).strip().lower()

    if pd.isna(position):
        position = pd.to_numeric(row.get("position_12m"), errors="coerce")

    if pd.isna(position):
        position = 99.0
    if pd.isna(ctr):
        ctr = 0.0

    if position >= 30:
        return {
            "code": RECOMMENDED_ACTION_FULL_REFRESH,
            "reason": "ranking is deep in search results",
        }

    if trend in {"volatile", "declining"}:
        if position >= 20:
            return {
                "code": RECOMMENDED_ACTION_FULL_REFRESH,
                "reason": "volatile or declining trend with weak second-page ranking",
            }
        return {
            "code": RECOMMENDED_ACTION_TITLE_META,
            "reason": "borderline second-page ranking with unstable trend",
        }

    if trend in {"improving", "continuously_good"}:
        if ctr >= 0.025:
            return {
                "code": RECOMMENDED_ACTION_TITLE_META,
                "reason": "healthy trend with acceptable CTR",
            }
        return {
            "code": RECOMMENDED_ACTION_CONTENT_PLUS_META,
            "reason": "improving page needs content and snippet refresh",
        }

    return {
        "code": RECOMMENDED_ACTION_CONTENT_PLUS_META,
        "reason": "balanced refresh needed for content and snippet",
    }


def clean_recommendation_reason(reason: str) -> str:
    """Normalize recommendation text to a short, compact phrase."""
    text = " ".join(str(reason).strip().split())
    text = re.sub(r"^reason:\s*", "", text, flags=re.IGNORECASE)
    text = text.rstrip(".")
    for separator in (";", ",", ". "):
        if separator in text:
            text = text.split(separator, 1)[0].strip()
            break
    words = text.split()
    if len(words) > MAX_REASON_WORDS:
        text = " ".join(words[:MAX_REASON_WORDS])
    return text


def parse_recommendation_response(raw_text: str) -> dict | None:
    """Parse the LLM response into the structured cell value we want to store."""
    if not raw_text:
        return None

    text = raw_text.strip()
    if text.startswith("```"):
        text = text.strip("`").strip()

    try:
        parsed = json.loads(text)
        if isinstance(parsed, dict):
            action = str(
                parsed.get("recommended_action_code")
                or parsed.get("recommended_action")
                or parsed.get("action")
                or ""
            ).strip()
            reason = str(parsed.get("reason", "")).strip()
            code = normalize_recommended_action_code(action)
            if code:
                return {
                    "code": code,
                    "reason": clean_recommendation_reason(reason) if reason else "",
                }
    except json.JSONDecodeError:
        pass

    if "|" in text:
        action, reason = text.split("|", 1)
        code = normalize_recommended_action_code(action)
        reason = clean_recommendation_reason(reason)
        if code:
            return {"code": code, "reason": reason}

    code = normalize_recommended_action_code(text)
    if code:
        return {"code": code, "reason": ""}

    reason = clean_recommendation_reason(text)
    if reason:
        return {"code": RECOMMENDED_ACTION_CONTENT_PLUS_META, "reason": reason}

    return None


_recommendation_cache = {}


def recommend_action_info(row, period_labels, client=None, allow_llm: bool = True) -> dict:
    """Generate a structured action recommendation using LLM when available."""
    signature = build_recommendation_signature(row, period_labels)
    if signature in _recommendation_cache:
        return _recommendation_cache[signature]

    position = row.get("min_position_any_period", "")
    ctr_12m = row.get("ctr_12m", "")
    clicks_12m = row.get("clicks_12m", "")
    impressions_12m = row.get("impressions_12m", "")
    trend = row.get("trend_pattern", "")
    days_since_published = row.get("days_since_published", "")

    fallback = fallback_recommended_action(row)
    if not allow_llm:
        _recommendation_cache[signature] = fallback
        return fallback

    client = client or RECOMMENDATION_CLIENT
    if client is None:
        _recommendation_cache[signature] = fallback
        return fallback

    prompt = f"""
You are recommending the next optimization strategy for a blog post.
Return only JSON with keys:
- recommended_action_code
- reason

The action code must be one of:
- {RECOMMENDED_ACTION_TITLE_META}
- {RECOMMENDED_ACTION_FULL_REFRESH}
- {RECOMMENDED_ACTION_CONTENT_PLUS_META}

The reason must be a short fragment of at most {MAX_REASON_WORDS} words.
Do not include the word "Reason:" in the value.

Use the metrics below to decide.
URL: {row.get('page', '')}
Clicks (12m): {clicks_12m}
Impressions (12m): {impressions_12m}
CTR (12m): {ctr_12m}
Position (best across periods): {position}
Trend pattern: {trend}
Days since published: {days_since_published}

Guidance:
- Use {RECOMMENDED_ACTION_TITLE_META} when the page is near the second-page boundary and mostly needs a better snippet.
- Use {RECOMMENDED_ACTION_FULL_REFRESH} when trend is volatile or declining, or the page is far beyond page one.
- Use {RECOMMENDED_ACTION_CONTENT_PLUS_META} when both content and metadata should be refreshed.
- Keep the reason short: a fragment, not a sentence.

Example:
{{"recommended_action_code":"{RECOMMENDED_ACTION_TITLE_META}","reason":"borderline second-page ranking with unstable trend"}}
{{"recommended_action_code":"{RECOMMENDED_ACTION_FULL_REFRESH}","reason":"volatile or declining trend with weak second-page ranking"}}
""".strip()

    try:
        response = client.chat.completions.create(
            model=LLM_MODEL,
            messages=[
                {
                    "role": "system",
                    "content": "You are a strict blog optimization strategist. Return JSON only.",
                },
                {"role": "user", "content": prompt},
            ],
            temperature=0.2,
            max_tokens=120,
            timeout=20.0,
        )
        raw_text = (response.choices[0].message.content or "").strip()
        recommendation = parse_recommendation_response(raw_text)
        if recommendation:
            _recommendation_cache[signature] = recommendation
            return recommendation
    except Exception as exc:
        print(f"  Warning: recommendation LLM failed for {row.get('page', '')}: {exc}")

    _recommendation_cache[signature] = fallback
    return fallback


def recommend_action(row, period_labels, client=None, allow_llm: bool = True) -> str:
    """Backward-compatible wrapper that returns only the action code."""
    return recommend_action_info(row, period_labels, client=client, allow_llm=allow_llm)["code"]


def build_wide_table(period_dfs: dict) -> pd.DataFrame:
    """
    Merge per-period DataFrames into a single wide table keyed on 'page'.
    Suffix each metric column with the period label.
    """
    merged = None
    for label, df in period_dfs.items():
        renamed = df.rename(columns={
            "clicks":      f"clicks_{label}",
            "impressions": f"impressions_{label}",
            "ctr":         f"ctr_{label}",
            "position":    f"position_{label}",
        })
        if merged is None:
            merged = renamed
        else:
            merged = merged.merge(renamed, on="page", how="outer")

    return merged.reset_index(drop=True)


def enrich_publish_age(df: pd.DataFrame) -> pd.DataFrame:
    """Add 'days_since_published' column via local content repo, if available."""
    content_root, days_map, parsed, matched, total, _ = select_best_days_since_map(
        CONTENT_REPO_NAME, df["page"].tolist()
    )
    if content_root:
        print(f"  Content root: {content_root}")
        print(f"  Indexed {parsed:,} posts; matched {matched:,}/{total:,} URLs")
    else:
        print("  Content root not found — skipping publish-age enrichment.")
        days_map = {}

    df["days_since_published"] = df["page"].apply(
        lambda p: days_map.get(url_to_path(str(p)))
    )
    return df


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("=" * 70)
    print(f"GSC Multi-Period Comparison Agent — {PROPERTY_HOST}")
    print("=" * 70)

    # 1) Authenticate
    print("\nAuthenticating …")
    try:
        account = authenticate()
        print("  Auth OK")
    except Exception as exc:
        print(f"  Auth failed: {exc}")
        sys.exit(1)

    try:
        webproperty = account[PROPERTY_URL]
    except KeyError:
        print(f"Property '{PROPERTY_URL}' not found. Available: {list(account)}")
        sys.exit(1)

    # 2) Fetch all periods
    print("\nFetching data from Search Console …")
    period_dfs = {}
    for label, days_back in PERIODS:
        try:
            period_dfs[label] = fetch_period(webproperty, days_back, label)
        except Exception as exc:
            print(f"  [{label}] Fetch failed: {exc}")
            period_dfs[label] = pd.DataFrame(
                columns=["page", "clicks", "impressions", "ctr", "position"]
            )

    # 3) Merge into wide table
    print("\nMerging periods …")
    period_labels = [label for label, _ in PERIODS]   # ["3m", "6m", "12m"]
    wide = build_wide_table(period_dfs)
    print(f"  {len(wide):,} unique URLs across all periods")

    # 4) Trend pattern
    wide["trend_pattern"] = wide.apply(
        lambda row: label_trend(row, period_labels), axis=1
    )

    # 5) High-click flag  (any period >= threshold)
    click_cols = [f"clicks_{p}" for p in period_labels]
    wide["max_clicks_any_period"] = wide[click_cols].max(axis=1)
    wide["high_click_url"] = wide["max_clicks_any_period"] >= HIGH_CLICK_THRESHOLD
    wide["min_position_any_period"] = wide.apply(
        lambda row: min_position_across_periods(row, period_labels), axis=1
    )
    wide["position_ok"] = wide["min_position_any_period"] >= POSITION_THRESHOLD

    # 6) Enrich with publish age
    print("\nEnriching with publish dates …")
    wide = enrich_publish_age(wide)

    # 7) Column order for wide/all table
    ordered_cols = ["page"]
    for p in period_labels:
        ordered_cols += [f"clicks_{p}", f"impressions_{p}", f"ctr_{p}", f"position_{p}"]
    ordered_cols += [
        "trend_pattern",
        "max_clicks_any_period",
        "high_click_url",
        "min_position_any_period",
        "position_ok",
        "days_since_published",
    ]
    # Keep any extra columns that might exist
    extra = [c for c in wide.columns if c not in ordered_cols]
    wide = wide[ordered_cols + extra]

    # 8) Save CSV 1 — all URLs with all periods
    os.makedirs(CSV_FOLDER, exist_ok=True)
    all_path = os.path.join(CSV_FOLDER, "comparison_all_periods.csv")
    wide.sort_values("days_since_published", ascending=False, na_position="last", inplace=True)
    wide.to_csv(all_path, index=False)
    print(f"\nSaved: {all_path}  ({len(wide):,} rows)")

    # 9) Filter to optimization candidates
    # Anchor on 12m CTR band; exclude high-click; keep only URLs that appear
    # in the 12m data so we have a stable anchor
    anchor = "12m"
    ctr_anchor = f"ctr_{anchor}"
    clicks_anchor = f"clicks_{anchor}"

    candidates = wide.copy()

    # Must exist in anchor period
    candidates = candidates[candidates[ctr_anchor].notna()]

    # CTR band in anchor period
    candidates = candidates[
        (candidates[ctr_anchor] >= CTR_THRESHOLD) &
        (candidates[ctr_anchor] <= CTR_MAX_THRESHOLD)
    ]

    # Exclude high-click URLs
    before_hc = len(candidates)
    candidates = candidates[~candidates["high_click_url"]]
    hc_removed = before_hc - len(candidates)

    # Exclude URLs that rank too well in any available period
    before_pos = len(candidates)
    candidates = candidates[candidates["position_ok"]]
    pos_removed = before_pos - len(candidates)

    print(f"\nCandidates filter:")
    print(f"  CTR {CTR_THRESHOLD:.0%}–{CTR_MAX_THRESHOLD:.0%} in {anchor} window → {before_hc:,} URLs")
    print(f"  Removed {hc_removed:,} high-click URLs (>= {HIGH_CLICK_THRESHOLD} clicks in any period)")
    print(f"  Removed {pos_removed:,} URLs with position < {POSITION_THRESHOLD} in any available period")
    print(f"  Final candidates: {len(candidates):,} URLs")

    # Recommend the next optimization strategy for each candidate.
    print("\n  Generating recommended actions …")
    recommendation_series = candidates.apply(
        lambda row: recommend_action_info(row, period_labels), axis=1
    )
    candidates[RECOMMENDED_ACTION_REASON_COLUMN] = recommendation_series.apply(
        lambda item: item.get("reason", "") if isinstance(item, dict) else ""
    )
    candidates[RECOMMENDED_ACTION_COLUMN] = recommendation_series.apply(
        lambda item: item.get("code", RECOMMENDED_ACTION_CONTENT_PLUS_META)
        if isinstance(item, dict)
        else RECOMMENDED_ACTION_CONTENT_PLUS_META
    )

    # Keep the structured recommendation as the last column for readability in Excel.
    candidate_cols = [
        c for c in candidates.columns
        if c not in {RECOMMENDED_ACTION_COLUMN, RECOMMENDED_ACTION_REASON_COLUMN}
    ]
    candidates = candidates[
        candidate_cols + [RECOMMENDED_ACTION_REASON_COLUMN, RECOMMENDED_ACTION_COLUMN]
    ]

    # Pattern breakdown
    print("\n  Trend pattern breakdown:")
    for pattern, count in candidates["trend_pattern"].value_counts().items():
        print(f"    {pattern:<22} {count:>5}")

    candidate_csv_stem = derive_candidate_csv_stem(PROPERTY_URL)
    cand_path = os.path.join(CSV_FOLDER, f"{candidate_csv_stem}.csv")
    candidates.to_csv(cand_path, index=False)
    print(f"\nSaved: {cand_path}  ({len(candidates):,} rows)")

    # 10) Upload to Google Sheets using the full CSV payload.
    print("\nUploading candidate CSV to Google Sheets …")
    upload_rows = [clean_row_record(record) for record in candidates.to_dict(orient="records")]
    upload_success = True
    final_upload_result = None
    if upload_rows:
        total_chunks = (len(upload_rows) - 1) // UPLOAD_CHUNK_SIZE + 1
        for i in range(0, len(upload_rows), UPLOAD_CHUNK_SIZE):
            chunk = upload_rows[i : i + UPLOAD_CHUNK_SIZE]
            chunk_num = i // UPLOAD_CHUNK_SIZE + 1
            print(f"  Upload chunk {chunk_num}/{total_chunks} ({len(chunk):,} rows)")
            chunk_ok, result = send_to_google_sheets(chunk, is_first_chunk=(i == 0))
            if not chunk_ok:
                upload_success = False
                break
            final_upload_result = result
    else:
        print("  No candidate rows to upload.")

    # 11) Summary
    print("\n" + "=" * 70)
    print("Done.")
    print(f"  {all_path}  — full picture, all URLs, all periods")
    print(f"  {cand_path} — filtered optimization candidates with trend labels")
    if upload_rows:
        if upload_success:
            print(f"  Uploaded {len(upload_rows):,} rows to {SHEET_NAME}")
            if final_upload_result and "spreadsheet_url" in final_upload_result:
                print(f"  Sheet URL: {final_upload_result['spreadsheet_url']}")
        else:
            print("  Upload failed partway through.")
    print("=" * 70)


if __name__ == "__main__":
    main()
